### PR TITLE
improve ui and resolve newline omitted problem

### PR DESCRIPTION
**Pull request by TianYong-Goh**
-resolve ui where newline being omitted in history page
-improve ui where there is no history record for the user

### CODE REVIEW

**Review by hopinxian — CHANGES_REQUESTED** [review]
Tabs and consecutive spaces arent preserved.

Expected:
expected

Actual:
actual

**Comment by TianYong-Goh** [comment]
> Tabs and consecutive spaces arent preserved.
> 
> Expected: expected
> 
> Actual: actual

-fixed and pushed

**Comment by oliviajohansen** [comment]
could you also add which users collaborated on the code for each history since we already have the data

**Comment by TianYong-Goh** [comment]
> could you also add which users collaborated on the code for each history since we already have the data

ok. I will add it in.

**Review by hopinxian — APPROVED** [review]
LGTM

**Pull request merged**
